"""Intraday trading configuration."""
TOTAL_BUDGET = 2500  # € (5 bots x 500)

COMMISSION_RATES = {
    "kraken": 0.0026,   # 0.26% taker fee (Kraken réel)
}

BOTS = [
    {
        "name": "crypto_scalper",
        "strategy": "crypto_scalper",
        "budget": 500,
        "display_name": "Crypto Scalper",
        "timeframe": 1,
        "symbols": ["XBT/USD", "ETH/USD", "SOL/USD"],
        "data_source": "kraken",
        "description": "Scalping 1min sur BTC, ETH, SOL. Suit les croisements EMA5/EMA12 (moyennes mobiles exponentielles rapides). Achète quand la moyenne 5min dépasse la 12min à la hausse (golden cross), vend quand elle passe en dessous (death cross). Stop-loss -0.8%, take-profit +2.0%, max 5 positions, 10% du cash par position."
    },
    {
        "name": "crypto_mean_rev",
        "strategy": "crypto_mean_rev",
        "budget": 500,
        "display_name": "Crypto Mean Reversion",
        "timeframe": 5,
        "symbols": ["SOL/USD", "XRP/USD", "ADA/USD", "AVAX/USD", "DOT/USD",
                    "LINK/USD", "ATOM/USD", "NEAR/USD", "APT/USD", "SUI/USD",
                    "AAVE/USD", "UNI/USD", "DOGE/USD", "SHIB/USD", "BCH/USD",
                    "LTC/USD", "TRX/USD", "ETC/USD", "XLM/USD", "ALGO/USD"],
        "data_source": "kraken",
        "description": "Mean reversion 5min sur 20 altcoins. Surveille le RSI (Relative Strength Index) sur 14 périodes de 5min. Achète quand RSI < 25 (survendu - rebound probable), vend quand RSI > 70 (retour à la normale). Max 8 positions simultanées par bot (POSITION_PCT = 10% du cash par position)."
    },
    {
        "name": "crypto_momentum",
        "strategy": "crypto_momentum",
        "budget": 500,
        "display_name": "Crypto Momentum",
        "timeframe": 15,
        "symbols": [
                    "AAVE/USD",
                    "ADA/USD",
                    "ADI/USD",
                    "ALGO/USD",
                    "APT/USD",
                    "ARB/USD",
                    "ASTER/USD",
                    "ATOM/USD",
                    "AVAX/USD",
                    "BCH/USD",
                    "BDX/USD",
                    "BGB/USD",
                    "BNB/USD",
                    "CC/USD",
                    "CRO/USD",
                    "DAI/USD",
                    "DOT/USD",
                    "ENA/USD",
                    "ETC/USD",
                    "ETH/USD",
                    "FIL/USD",
                    "FLR/USD",
                    "HBAR/USD",
                    "HYPE/USD",
                    "ICP/USD",
                    "JST/USD",
                    "JUP/USD",
                    "KAS/USD",
                    "LINK/USD",
                    "LIT/USD",
                    "LTC/USD",
                    "M/USD",
                    "MNT/USD",
                    "MORPHO/USD",
                    "NEAR/USD",
                    "OKB/USD",
                    "ONDO/USD",
                    "PAXG/USD",
                    "PEPE/USD",
                    "PI/USD",
                    "POL/USD",
                    "PUMP/USD",
                    "PYUSD/USD",
                    "QNT/USD",
                    "RAIN/USD",
                    "RENDER/USD",
                    "RLUSD/USD",
                    "SHIB/USD",
                    "SKY/USD",
                    "SOL/USD",
                    "STABLE/USD",
                    "SUI/USD",
                    "TAO/USD",
                    "TRX/USD",
                    "U/USD",
                    "UNI/USD",
                    "USD1/USD",
                    "USDC/USD",
                    "USDD/USD",
                    "USDE/USD",
                    "USDG/USD",
                    "USDS/USD",
                    "USDT/USD",
                    "WBT/USD",
                    "WLD/USD",
                    "WLFI/USD",
                    "XAUT/USD",
                    "XBT/USD",
                    "XDC/USD",
                    "XLM/USD",
                    "XMR/USD",
                    "XRP/USD",
                    "ZEC/USD"
        ],
        "data_source": "kraken",
        "description": "Momentum 15min sur les cryptos CoinGecko top 100 (>$1M market cap). Calcule la performance des 15 dernières minutes. Achète les 5 meilleures performances, vend les positions sorties du top. 12% du cash par position."
    },
    {
        "name": "crypto_dip_buyer",
        "strategy": "dip_buyer",
        "budget": 500,
        "display_name": "Crypto Dip Buyer",
        "timeframe": 5,
        "symbols": [
                    "AAVE/USD",
                    "ADA/USD",
                    "ADI/USD",
                    "ALGO/USD",
                    "APT/USD",
                    "ARB/USD",
                    "ASTER/USD",
                    "ATOM/USD",
                    "AVAX/USD",
                    "BCH/USD",
                    "BDX/USD",
                    "BGB/USD",
                    "BNB/USD",
                    "CC/USD",
                    "CRO/USD",
                    "DAI/USD",
                    "DOT/USD",
                    "ENA/USD",
                    "ETC/USD",
                    "ETH/USD",
                    "FIL/USD",
                    "FLR/USD",
                    "HBAR/USD",
                    "HYPE/USD",
                    "ICP/USD",
                    "JST/USD",
                    "JUP/USD",
                    "KAS/USD",
                    "LINK/USD",
                    "LIT/USD",
                    "LTC/USD",
                    "M/USD",
                    "MNT/USD",
                    "MORPHO/USD",
                    "NEAR/USD",
                    "OKB/USD",
                    "ONDO/USD",
                    "PAXG/USD",
                    "PEPE/USD",
                    "PI/USD",
                    "POL/USD",
                    "PUMP/USD",
                    "PYUSD/USD",
                    "QNT/USD",
                    "RAIN/USD",
                    "RENDER/USD",
                    "RLUSD/USD",
                    "SHIB/USD",
                    "SKY/USD",
                    "SOL/USD",
                    "STABLE/USD",
                    "SUI/USD",
                    "TAO/USD",
                    "TRX/USD",
                    "U/USD",
                    "UNI/USD",
                    "USD1/USD",
                    "USDC/USD",
                    "USDD/USD",
                    "USDE/USD",
                    "USDG/USD",
                    "USDS/USD",
                    "USDT/USD",
                    "WBT/USD",
                    "WLD/USD",
                    "WLFI/USD",
                    "XAUT/USD",
                    "XBT/USD",
                    "XDC/USD",
                    "XLM/USD",
                    "XMR/USD",
                    "XRP/USD",
                    "ZEC/USD"
        ],
        "data_source": "kraken",
        "description": "Contrarian dip-buying 5min sur top 100 CoinGecko (>$1M market cap). Achète quand le prix baisse de ≥3% sur 20 bougies ET qu'un rebond se confirme (2/3 dernières bougies vertes, clôture > ouverture précédente). Take-profit +2%, stop-loss -2%, timeout 10 bougies. Max 5 positions, 10% du cash par position."
    },
    {
        "name": "crypto_social_momentum",
        "strategy": "social_momentum",
        "budget": 500,
        "display_name": "Crypto Social Momentum",
        "timeframe": 30,
        "symbols": [
                    "AAVE/USD",
                    "ADA/USD",
                    "ADI/USD",
                    "ALGO/USD",
                    "APT/USD",
                    "ARB/USD",
                    "ASTER/USD",
                    "ATOM/USD",
                    "AVAX/USD",
                    "BCH/USD",
                    "BDX/USD",
                    "BGB/USD",
                    "BNB/USD",
                    "CC/USD",
                    "CRO/USD",
                    "DAI/USD",
                    "DOT/USD",
                    "ENA/USD",
                    "ETC/USD",
                    "ETH/USD",
                    "FIL/USD",
                    "FLR/USD",
                    "HBAR/USD",
                    "HYPE/USD",
                    "ICP/USD",
                    "JST/USD",
                    "JUP/USD",
                    "KAS/USD",
                    "LINK/USD",
                    "LIT/USD",
                    "LTC/USD",
                    "M/USD",
                    "MNT/USD",
                    "MORPHO/USD",
                    "NEAR/USD",
                    "OKB/USD",
                    "ONDO/USD",
                    "PAXG/USD",
                    "PEPE/USD",
                    "PI/USD",
                    "POL/USD",
                    "PUMP/USD",
                    "PYUSD/USD",
                    "QNT/USD",
                    "RAIN/USD",
                    "RENDER/USD",
                    "RLUSD/USD",
                    "SHIB/USD",
                    "SKY/USD",
                    "SOL/USD",
                    "STABLE/USD",
                    "SUI/USD",
                    "TAO/USD",
                    "TRX/USD",
                    "U/USD",
                    "UNI/USD",
                    "USD1/USD",
                    "USDC/USD",
                    "USDD/USD",
                    "USDE/USD",
                    "USDG/USD",
                    "USDS/USD",
                    "USDT/USD",
                    "WBT/USD",
                    "WLD/USD",
                    "WLFI/USD",
                    "XAUT/USD",
                    "XBT/USD",
                    "XDC/USD",
                    "XLM/USD",
                    "XMR/USD",
                    "XRP/USD",
                    "ZEC/USD"
        ],
        "data_source": "kraken",
        "description": "Social momentum 30min via CoinGecko trending. Détecte les cryptos qui gagnent en popularité sur les réseaux sociaux (proxy X.com). Achète quand un token entre dans le top 5 trending, vend quand il sort du top 20. Max 5 positions, 12% du cash par position."
    },
]

# Collect all unique Kraken symbols across all bots for the WebSocket feed
CRYPTO_SYMBOLS = sorted(set(
    s for bot in BOTS for s in bot["symbols"] if "/USD" in s
))

ALPACA_SYMBOLS = []
